"""
Moving Averages & Exponential Smoothing Trend Extraction Tool

This module provides a general-purpose, reusable framework for conducting Exploratory
Data Analysis (EDA) on time-series sequences using temporal smoothing filters. It
automates pipeline calculations for Simple Moving Averages (SMA) and Exponentially Weighted
Moving Averages (EWMA), handles initial boundary gaps via adjustable minimum periods, and
outputs clean, publication-grade trend overlay visualizations independent of specific datasets.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


def calculate_temporal_smoothing(
    series: pd.Series,
    window: int = 30,
    min_periods: int = None
) -> pd.DataFrame:
    """
    Computes Simple Moving Average (SMA) and Exponentially Weighted Moving 
    Average (EWMA) tracking metrics for a time series.
    
    Parameters:
    -----------
    series : pd.Series
        The chronological numerical time series to process.
    window : int, default=30
        The size of the lookback window or span (W) for the tracking filters.
    min_periods : int, optional
        Minimum observations in window required to write a value. If None, 
        defaults to the full window size, resulting in early boundary NaNs.
        
    Returns:
    --------
    pd.DataFrame
        A DataFrame containing the raw observed data alongside computed SMA 
        and EWMA metrics.
    """
    if not isinstance(series, pd.Series):
        raise TypeError("Input 'series' must be a pandas Series object.")
    if window <= 0:
        raise ValueError("The window size parameter must be a positive integer greater than zero.")
        
    # Clean out internal missing entries using linear time interpolation
    clean_series = series.copy()
    if clean_series.isnull().any():
        clean_series = clean_series.interpolate(method="time")
        
    results_df = pd.DataFrame(index=clean_series.index)
    results_df["Observed"] = clean_series
    
    # Compute Simple Moving Average (equal weighting)
    results_df["SMA"] = clean_series.rolling(window=window, min_periods=min_periods).mean()
    
    # Compute Exponentially Weighted Moving Average (exponential decay weighting)
    results_df["EWMA"] = clean_series.ewm(span=window, adjust=False, min_periods=min_periods).mean()
    
    return results_df


def plot_temporal_smoothing_profile(
    metrics_df: pd.DataFrame,
    window_size: int,
    title_prefix: str = "Time Series",
    y_label: str = "Values",
    save_path: str = None
) -> None:
    """
    Generates a professional, publication-grade time-series visualization plot
    overlaying the original data with its smoothed SMA and EWMA trend representations.
    
    Parameters:
    -----------
    metrics_df : pd.DataFrame
        The output metric DataFrame generated by calculate_temporal_smoothing.
    window_size : int
        The lookback window size applied to the tracking metrics (used for label notation).
    title_prefix : str, default='Time Series'
        Descriptive name of the target variable for chart headers.
    y_label : str, default='Values'
        Text label for the vertical coordinate axis.
    save_path : str, optional
        File system destination path to save the completed figure file.
    """
    plt.figure(figsize=(12, 6.5))
    sns.set_theme(style="ticks")
    
    # Render the original observed data with soft transparency to highlight the filters
    plt.plot(metrics_df.index, metrics_df["Observed"], label="Observed Data", 
             color="#1f78b4", alpha=0.35, linewidth=1.5)
    
    # Overlay the Simple Moving Average line
    plt.plot(metrics_df.index, metrics_df["SMA"], label=f"Simple Moving Average (W={window_size})", 
             color="#d95f02", linewidth=2.0, linestyle="--")
             
    # Overlay the Exponentially Weighted Moving Average line
    plt.plot(metrics_df.index, metrics_df["EWMA"], label=f"Exponential Moving Average (Span={window_size})", 
             color="#2ca02c", linewidth=2.0, linestyle="-.")
             
    plt.title(f"{title_prefix}: Temporal Filtering & Smoothing Profile", fontsize=13, fontweight="bold", pad=15)
    plt.xlabel("Chronological Timeline Index", fontsize=11, labelpad=8)
    plt.ylabel(y_label, fontsize=11, labelpad=8)
    
    plt.grid(True, linestyle=":", alpha=0.5)
    plt.legend(loc="upper left", frameon=True, facecolor="white", edgecolor="none")
    
    sns.despine()
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300)
    plt.show()


if __name__ == "__main__":
    # Example usage with synthetically generated data to verify functionality
    np.random.seed(42)
    n_periods = 120
    time_index = pd.date_range(start="2025-01-01", periods=n_periods, freq="M")
    
    # Construct a synthetic time series with a steady upward trend and seasonal oscillations
    base_signal = np.linspace(50, 85, n_periods)
    seasonal_cycle = 7.0 * np.sin(2 * np.pi * np.arange(n_periods) / 12)
    stochastic_noise = np.random.normal(0, 2.5, size=n_periods)
    
    # Inject an abrupt noise shock spike to test filter resilience
    stochastic_noise[60] = 18.0
    
    mock_values = base_signal + seasonal_cycle + stochastic_noise
    mock_series = pd.Series(mock_values, index=time_index, name="Core_Metric")
    
    print("--- 1. Executing Temporal Smoothing Pipeline (Window=12) ---")
    # Setting min_periods=None to demonstrate standard startup lookback truncation
    smoothing_dataframe = calculate_temporal_smoothing(mock_series, window=12, min_periods=None)
    print("Smoothed metrics matrix preview (showing early boundary NaNs for SMA):")
    print(smoothing_dataframe.head(14))
    
    print("
--- 2. Launching Trend Filtering Visualization Overlay ---")
    plot_temporal_smoothing_profile(
        metrics_df=smoothing_dataframe,
        window_size=12,
        title_prefix="Simulated Operational Performance Index",
        y_label="Metric Scaling Units"
    )