"""
Hodrick-Prescott Filter Analysis & Trend-Cycle Decomposition Tool

This module provides a general-purpose, reusable framework for conducting Exploratory
Data Analysis (EDA) on macroeconomic and financial time-series using the Hodrick-Prescott
(HP) Filter. It automates missing data cleansing, handles lambda parameters across
various data frequencies, executes the trend-cycle decomposition, and generates clean,
professional multi-panel diagnostic visualizations independent of specific datasets.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.filters.hp_filter import hpfilter


def execute_hp_decomposition(
    series: pd.Series, 
    lambda_param: float = None, 
    frequency_hint: str = "Q"
) -> dict:
    """
    Validates data, determines the appropriate lambda smoothing parameter, 
    and applies the Hodrick-Prescott filter to separate trend and cyclical components.
    
    Parameters:
    -----------
    series : pd.Series
        The input continuous numerical time series to decompose.
    lambda_param : float, optional
        The smoothing parameter (lambda). If omitted, the function automatically 
        assigns a standard baseline value based on the 'frequency_hint'.
    frequency_hint : str, default='Q'
        The sampling interval hint used if lambda_param is None:
        'A' or 'Y' -> Annual (lambda=100)
        'Q'        -> Quarterly (lambda=1600)
        'M'        -> Monthly (lambda=14400)
        
    Returns:
    --------
    dict
        A dictionary containing the clean observed series, extracted trend, 
        extracted cycle, and the chosen lambda value.
    """
    if not isinstance(series, pd.Series):
        raise TypeError("The input 'series' parameter must be a pandas Series object.")
        
    # Clean out internal missing entries using continuous time-based interpolation
    clean_series = series.copy()
    if clean_series.isnull().any():
        clean_series = clean_series.interpolate(method="time")
    clean_series = clean_series.dropna()
    
    if clean_series.empty:
        raise ValueError("The time series is empty after removing missing values.")
        
    # Automatically assign standard lambda values if not explicitly provided
    if lambda_param is None:
        freq = str(frequency_hint).upper()[0]
        if freq in ["A", "Y"]:
            lambda_param = 100.0
        elif freq == "Q":
            lambda_param = 1600.0
        elif freq == "M":
            lambda_param = 14400.0
        else:
            print(f"Warning: Unknown frequency hint '{frequency_hint}'. Defaulting lambda to 1600 (Quarterly).")
            lambda_param = 1600.0
            
    # Apply the Hodrick-Prescott filter optimization solver
    cycle_component, trend_component = hpfilter(clean_series, lamb=lambda_param)
    
    return {
        "observed": clean_series,
        "trend": trend_component,
        "cycle": cycle_component,
        "lambda_applied": lambda_param
    }


def plot_hp_decomposition(
    hp_results: dict, 
    title_prefix: str = "Time Series", 
    y_label: str = "Value", 
    save_path: str = None
) -> None:
    """
    Generates a professional 2-panel stacked diagnostic plot layout.
    The top panel overlays the raw data with the smooth trend component, 
    while the bottom panel tracks the zero-centered cyclical fluctuations.
    
    Parameters:
    -----------
    hp_results : dict
        The output metric dictionary generated by execute_hp_decomposition.
    title_prefix : str, default="Time Series"
        Descriptive name of the target variable for chart headers.
    y_label : str, default="Value"
        Text label for the vertical coordinate axes.
    save_path : str, optional
        File system destination path to save the completed figure file.
    """
    observed = hp_results["observed"]
    trend = hp_results["trend"]
    cycle = hp_results["cycle"]
    lamb = hp_results["lambda_applied"]
    
    # Initialize a 2-panel vertically stacked grid layout
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), sharex=True, gridspec_kw={'height_ratios': [2, 1]})
    
    # --- Top Plot: Trend Component Overlay ---
    ax1.plot(observed.index, observed.values, label="Observed Data", color="#1f78b4", alpha=0.4, linewidth=1.5)
    ax1.plot(trend.index, trend.values, label=f"HP Trend Component (λ={lamb})", color="#e31a1c", linewidth=2.0, linestyle="--")
    ax1.set_title(f"{title_prefix}: Long-Term Trend Component Extraction", fontsize=12, fontweight="bold", loc="left")
    ax1.set_ylabel(y_label, fontsize=11)
    ax1.grid(True, linestyle=":", alpha=0.5)
    ax1.legend(loc="upper left", frameon=True, facecolor="white", edgecolor="none")
    
    # --- Bottom Plot: Cyclical Component ---
    ax2.plot(cycle.index, cycle.values, label="Cyclical Fluctuations", color="#2ca02c", linewidth=1.5)
    ax2.axhline(0, color="black", linestyle="-", linewidth=0.8, alpha=0.6)
    ax2.set_title(f"{title_prefix}: Short-Term Cyclical Component (Business Cycle Deviation)", fontsize=12, fontweight="bold", loc="left")
    ax2.set_ylabel("Cyclical Deviation", fontsize=11)
    ax2.set_xlabel("Timeline Index", fontsize=11)
    ax2.grid(True, linestyle=":", alpha=0.5)
    ax2.legend(loc="upper left", frameon=True, facecolor="white", edgecolor="none")
    
    sns.despine(ax=ax1)
    sns.despine(ax=ax2)
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300)
    plt.show()


if __name__ == "__main__":
    # Example usage with synthetically generated data to verify functionality
    np.random.seed(42)
    n_periods = 80
    time_index = pd.date_range(start="2005-01-01", periods=n_periods, freq="Q")
    
    # Construct a synthetic time series containing a smooth upward trend and an annual cycle
    underlying_growth = np.linspace(150, 320, n_periods)
    cyclical_shocks = 18.0 * np.sin(2 * np.pi * np.arange(n_periods) / 16) + np.random.normal(0, 4.0, size=n_periods)
    
    mock_values = underlying_growth + cyclical_shocks
    mock_series = pd.Series(mock_values, index=time_index, name="Simulated_Macro_Metric")
    
    print("--- 1. Executing Hodrick-Prescott Filter Pipeline (Quarterly Standard) ---")
    decomposition_results = execute_hp_decomposition(mock_series, lambda_param=1600.0)
    print("Decomposition completed successfully. Component head preview:")
    print(pd.DataFrame({
        "Observed": decomposition_results["observed"],
        "Trend": decomposition_results["trend"],
        "Cycle": decomposition_results["cycle"]
    }).tail())
    
    print("
--- 2. Launching Stacked Diagnostic Visualizations ---")
    plot_hp_decomposition(
        hp_results=decomposition_results, 
        title_prefix="Simulated Aggregated GDP Index", 
        y_label="Index Metric Values"
    )