"""
Rolling vs. Expanding Window Statistics & Filtering Tool

This module provides a general-purpose, reusable framework for conducting Exploratory
Data Analysis (EDA) on time-series sequences using moving and growing window statistics.
It automates the pipeline execution for Simple Rolling Means, Expanding Means, localized 
volatility intervals, and difference tracking, outputting professional diagnostic plots 
independent of specific project datasets.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


def compute_window_statistics(
    series: pd.Series,
    rolling_window: int = 30,
    min_periods: int = 1
) -> pd.DataFrame:
    """
    Computes rolling and expanding statistical tracking metrics for a time series.
    
    Parameters:
    -----------
    series : pd.Series
        The chronological numerical time series to process.
    rolling_window : int, default=30
        The size of the moving lookback window (W) for rolling statistics.
    min_periods : int, default=1
        Minimum observations in window required to write a value. Setting to 1 
        prevents missing data gaps during the initial startup phase.
        
    Returns:
    --------
    pd.DataFrame
        A DataFrame containing the raw observed data alongside computed rolling 
        means, expanding means, rolling standard deviations, and metric gaps.
    """
    if not isinstance(series, pd.Series):
        raise TypeError("Input 'series' must be a pandas Series object.")
    if rolling_window <= 0:
        raise ValueError("The rolling window size must be a positive integer greater than zero.")
        
    # Clean out internal missing entries using linear time interpolation
    clean_series = series.copy()
    if clean_series.isnull().any():
        clean_series = clean_series.interpolate(method="time")
        
    results_df = pd.DataFrame(index=clean_series.index)
    results_df["Observed"] = clean_series
    
    # Compute central trends across sliding vs growing filters
    results_df["Rolling_Mean"] = clean_series.rolling(window=rolling_window, min_periods=min_periods).mean()
    results_df["Expanding_Mean"] = clean_series.expanding(min_periods=min_periods).mean()
    
    # Compute dynamic volatility profiles
    results_df["Rolling_Std"] = clean_series.rolling(window=rolling_window, min_periods=min_periods).std()
    
    # Calculate the gap deviation profile to identify structural drift
    results_df["Rolling_Expanding_Gap"] = results_df["Rolling_Mean"] - results_df["Expanding_Mean"]
    
    return results_df


def plot_window_profile_analysis(
    metrics_df: pd.DataFrame,
    title_prefix: str = "Time Series",
    save_path: str = None
) -> None:
    """
    Generates a professional 2-panel stacked diagnostic plot layout.
    The top panel overlays the raw data with the rolling and expanding trends, 
    while the bottom panel tracks the rolling-expanding structural gap.
    
    Parameters:
    -----------
    metrics_df : pd.DataFrame
        The output metric DataFrame generated by compute_window_statistics.
    title_prefix : str, default="Time Series"
        Descriptive name of the target variable for chart headers.
    save_path : str, optional
        File system destination path to save the completed figure file.
    """
    # Initialize a 2-panel vertically stacked grid layout
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), sharex=True, gridspec_kw={'height_ratios': [2.5, 1]})
    
    # --- Top Plot: Central Trends Overlay ---
    ax1.plot(metrics_df.index, metrics_df["Observed"], label="Observed Data", color="#1f78b4", alpha=0.3, linewidth=1.2)
    ax1.plot(metrics_df.index, metrics_df["Rolling_Mean"], label="Rolling Mean Filter", color="#d95f02", linewidth=2.0)
    ax1.plot(metrics_df.index, metrics_df["Expanding_Mean"], label="Expanding Mean Filter", color="#2ca02c", linewidth=2.0, linestyle="--")
    
    # Overlay optional soft volatility bands around the rolling mean
    upper_std = metrics_df["Rolling_Mean"] + (1.96 * metrics_df["Rolling_Std"])
    lower_std = metrics_df["Rolling_Mean"] - (1.96 * metrics_df["Rolling_Std"])
    ax1.fill_between(metrics_df.index, lower_std, upper_std, color="#d95f02", alpha=0.06, label="Rolling Volatility Band (±1.96σ)")
    
    ax1.set_title(f"{title_prefix}: Rolling vs. Expanding Window Statistics Profile", fontsize=13, fontweight="bold", loc="left")
    ax1.set_ylabel("Metric Values", fontsize=11)
    ax1.grid(True, linestyle=":", alpha=0.5)
    ax1.legend(loc="upper left", frameon=True, facecolor="white")
    
    # --- Bottom Plot: Structural Drift Gap ---
    ax2.plot(metrics_df.index, metrics_df["Rolling_Expanding_Gap"], label="Tracking Gap (Rolling - Expanding)", color="#7570b3", linewidth=1.5)
    ax2.axhline(0, color="black", linestyle="-", linewidth=0.8, alpha=0.5)
    
    ax2.set_ylabel("Gap Metric Matrix", fontsize=11)
    ax2.set_xlabel("Chronological Timeline Index", fontsize=11)
    ax2.grid(True, linestyle=":", alpha=0.5)
    ax2.legend(loc="upper left", frameon=True, facecolor="white")
    
    sns.despine(ax=ax1)
    sns.despine(ax=ax2)
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300)
    plt.show()


if __name__ == "__main__":
    # Example usage with synthetically generated data to verify functionality
    np.random.seed(42)
    n_days = 200
    time_index = pd.date_range(start="2024-01-01", periods=n_days, freq="D")
    
    # Generate a time series that experiences a distinct structural shift halfway through
    base_signal = np.linspace(40, 60, n_days)
    seasonal_cycle = 6 * np.sin(2 * np.pi * np.arange(n_days) / 30)
    stochastic_noise = np.random.normal(0, 2.5, size=n_days)
    
    # Inject a structural step shift at index 100 to simulate a market regime change
    structural_shift = np.zeros(n_days)
    structural_shift[100:] = 15.0
    
    mock_values = base_signal + seasonal_cycle + stochastic_noise + structural_shift
    mock_series = pd.Series(mock_values, index=time_index, name="Simulated_Metric")
    
    print("--- 1. Computing Dual Window Statistical Pipeline (Window=30) ---")
    window_metrics = compute_window_statistics(mock_series, rolling_window=30, min_periods=1)
    print(window_metrics[["Observed", "Rolling_Mean", "Expanding_Mean", "Rolling_Expanding_Gap"]].tail())
    
    print("
--- 2. Launching Stacked Diagnostic Visualizations ---")
    plot_window_profile_analysis(window_metrics, title_prefix="Simulated Operational Performance")