"""
Cross-Correlation Function (CCF) Analysis & Temporal Dependency Tool

This module provides a general-purpose, reusable framework for conducting Exploratory
Data Analysis (EDA) to measure time-lagged linear dependencies between two distinct 
time series. It handles chronological synchronization, optional differencing for trend 
removal, cross-correlation coefficient matrix mapping across positive and negative lag 
horizons, and renders professional diagnostic charts with statistical significance boundaries.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


def calculate_cross_correlation(
    x: pd.Series,
    y: pd.Series,
    max_lags: int = 24,
    difference_order: int = 0
) -> pd.DataFrame:
    """
    Synchronizes two series, applies optional trend-stabilizing differencing, and
    calculates cross-correlation coefficients across a spectrum of lookback/lookahead lags.
    
    A negative lag indicates that past values of X correlate with current values of Y (X leads Y).
    A positive lag indicates that current values of X correlate with past values of Y (X lags Y).
    
    Parameters:
    -----------
    x : pd.Series
        The independent/input time series (the reference variable).
    y : pd.Series
        The dependent/target time series (the tracking variable).
    max_lags : int, default=24
        The maximum number of lag steps to calculate in both directions.
    difference_order : int, default=0
        The number of differencing steps to apply to handle trends before analysis.
        
    Returns:
    --------
    pd.DataFrame
        A DataFrame indexed by lag values with columns for 'Correlation' coefficients 
        and 'Confidence_Band' significance limits.
    """
    # Align the two series onto a shared continuous index
    combined_df = pd.DataFrame({"X": x, "Y": y}).dropna()
    
    if combined_df.empty:
        raise ValueError("The aligned dataset is empty. Ensure both series share overlapping index intervals.")
        
    # Apply optional differencing to stabilize non-stationary trends
    if difference_order > 0:
        for _ in range(difference_order):
            combined_df = combined_df.diff()
        combined_df = combined_df.dropna()
        
    x_clean = combined_df["X"]
    y_clean = combined_df["Y"]
    n_samples = len(combined_df)
    
    if n_samples <= max_lags:
        raise ValueError(f"Sample size ({n_samples}) must be greater than max_lags ({max_lags}).")
        
    lags = range(-max_lags, max_lags + 1)
    correlations = []
    confidence_bands = []
    
    # Standardize individual elements to zero mean and unit variance for correlation mapping
    x_norm = (x_clean - x_clean.mean()) / x_clean.std()
    y_norm = (y_clean - y_clean.mean()) / y_clean.std()
    
    for lag in lags:
        if lag < 0:
            # X leads Y: Shift X backward (or shift Y forward)
            corr = x_norm.corr(y_norm.shift(lag))
        elif lag > 0:
            # X lags Y: Shift X forward (or shift Y backward)
            corr = x_norm.shift(lag).corr(y_norm)
        else:
            # Coincident instant interaction
            corr = x_norm.corr(y_norm)
            
        correlations.append(corr)
        # Calculate localized standard error boundaries (95% confidence rule)
        confidence_bands.append(1.96 / np.sqrt(n_samples - abs(lag)))
        
    results_df = pd.DataFrame({
        "Lag": lags,
        "Correlation": correlations,
        "Confidence_Band": confidence_bands
    }).set_index("Lag")
    
    return results_df


def plot_cross_correlation_function(
    ccf_df: pd.DataFrame,
    x_name: str = "Variable X",
    y_name: str = "Variable Y",
    title: str = "Bivariate Cross-Correlation Profile",
    save_path: str = None
) -> None:
    """
    Generates a professional Cross-Correlation Function (CCF) impulse plot with 
    shaded 95% confidence intervals and peak indicator highlights.
    
    Parameters:
    -----------
    ccf_df : pd.DataFrame
        The output metric DataFrame generated by calculate_cross_correlation.
    x_name : str, default="Variable X"
        Descriptive label for the reference input series.
    y_name : str, default="Variable Y"
        Descriptive label for the target tracking series.
    title : str, default="Bivariate Cross-Correlation Profile"
        The main descriptive title for the figure.
    save_path : str, optional
        File system destination path to save the completed figure file.
    """
    plt.figure(figsize=(11, 6))
    
    lags = ccf_df.index.values
    corrs = ccf_df["Correlation"].values
    bands = ccf_df["Confidence_Band"].values
    
    # Render the primary correlation coefficients as horizontal bar markers
    plt.bar(lags, corrs, color="#2b5c8f", width=0.4, alpha=0.85, label="Cross-Correlation", edgecolor="none")
    plt.plot(lags, corrs, color="#1f4e79", alpha=0.4, linestyle="-", linewidth=1)
    
    # Shading the 95% statistical significance confidence intervals
    plt.plot(lags, bands, color="#e31a1c", linestyle=":", alpha=0.7, linewidth=1.2)
    plt.plot(lags, -bands, color="#e31a1c", linestyle=":", alpha=0.7, linewidth=1.2)
    plt.fill_between(lags, -bands, bands, color="#e31a1c", alpha=0.06, label="95% Confidence Band")
    
    # Identify and highlight the absolute maximum relationship peak
    abs_corrs = np.abs(corrs)
    peak_idx = np.argmax(abs_corrs)
    peak_lag = lags[peak_idx]
    peak_val = corrs[peak_idx]
    
    if abs_corrs[peak_idx] > bands[peak_idx]:
        plt.scatter(peak_lag, peak_val, color="#d95f02", s=80, zorder=5, 
                    label=f"Significant Peak Lag {peak_lag} ({peak_val:.2f})")
        
    plt.axhline(0, color="gray", linestyle="-", linewidth=0.8, alpha=0.7)
    plt.axvline(0, color="gray", linestyle="--", linewidth=0.8, alpha=0.7)
    
    # Configure graph annotations and labels
    plt.title(title, fontsize=13, fontweight="bold", pad=15)
    plt.xlabel(f"Temporal Lag Steps (Negative = {x_name} leads {y_name})", fontsize=11, labelpad=8)
    plt.ylabel("Correlation Coefficient (r)", fontsize=11, labelpad=8)
    
    plt.xlim(lags.min() - 0.5, lags.max() + 0.5)
    plt.ylim(-1.05, 1.05)
    plt.grid(True, linestyle=":", alpha=0.4)
    plt.legend(loc="upper right", frameon=True, facecolor="white")
    
    sns.despine()
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300)
    plt.show()


if __name__ == "__main__":
    # Example usage with synthetically generated data to verify functionality
    np.random.seed(42)
    n_periods = 180
    time_idx = pd.date_range(start="2010-01-01", periods=n_periods, freq="M")
    
    # 1. Generate a baseline independent driving sequence (e.g., Production Cost index)
    independent_x = pd.Series(np.random.normal(0, 1.0, size=n_periods), index=time_idx)
    # Add an underlying random walk trend component to simulate real-world data
    independent_x = independent_x.cumsum()
    
    # 2. Generate a target tracking sequence where X leads Y by exactly 4 months
    # (Y checks the state of X from 4 steps back and adds independent noise)
    dependent_y = 1.5 * independent_x.shift(4) + pd.Series(np.random.normal(0, 2.0, size=n_periods), index=time_idx)
    dependent_y = dependent_y.dropna()
    
    print("--- 1. Evaluating Un-differenced Raw Time Series (Spurious Trend Trap) ---")
    raw_ccf = calculate_cross_correlation(independent_x, dependent_y, max_lags=15, difference_order=0)
    plot_cross_correlation_function(
        ccf_df=raw_ccf,
        x_name="Production Cost",
        y_name="Retail Price",
        title="CCF Analysis Profile (Raw Non-Stationary Series Data)"
    )
    
    print("
--- 2. Evaluating First-Differenced Series (True Structural Relationship Revealed) ---")
    # Applying first-differencing isolates the true operational lead-lag transmission delay
    clean_ccf = calculate_cross_correlation(independent_x, dependent_y, max_lags=15, difference_order=1)
    plot_cross_correlation_function(
        ccf_df=clean_ccf,
        x_name="Production Cost",
        y_name="Retail Price",
        title="CCF Analysis Profile (First-Differenced Stationary Data)"
    )