"""
Double Exponential Smoothing & Holt's Linear Trend Optimization Tool

This module provides a general-purpose, reusable framework for conducting Exploratory
Data Analysis (EDA) on time-series sequences using Double Exponential Smoothing and 
Holt's Linear Trend modeling. It automates chronological frequency verification, manages
missing data interpolation, runs recursive state-space filters, optimizes parameter 
selections, and generates clean, publication-grade diagnostic charts independent of 
specific datasets.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.holtwinters import ExponentialSmoothing


def apply_double_exponential_smoothing(
    series: pd.Series,
    frequency: str = None,
    alpha_span: int = None,
    optimize_parameters: bool = True
) -> dict:
    """
    Performs data cleaning, establishes uniform temporal steps, and executes
    Double Exponential Smoothing (Holt's Linear Trend) modeling.
    
    Parameters:
    -----------
    series : pd.Series
        The input time series featuring a valid pandas DatetimeIndex.
    frequency : str, optional
        The target frequency alias to enforce (e.g., 'D', 'M', 'Q'). If omitted,
        the function attempts to infer or preserve the index's native frequency.
    alpha_span : int, optional
        The memory lookback window span used if matching a Double EWMA configuration.
        Ignored if optimize_parameters is set to True.
    optimize_parameters : bool, default=True
        If True, utilizes statsmodels' internal MLE optimization routines to automatically
        calculate parameter settings that minimize squared estimation errors.
        
    Returns:
    --------
    dict
        A dictionary containing the clean series, fitted values, state components
        (isolated level and trend arrays), and a reference model object instance.
    """
    if not isinstance(series.index, pd.DatetimeIndex):
        raise ValueError("The input series index must be a valid pandas DatetimeIndex.")
        
    # Create a working copy and manage internal missing entries using time interpolation
    clean_series = series.copy()
    if clean_series.isnull().any():
        clean_series = clean_series.interpolate(method="time")
        
    # Enforce or infer uniform temporal frequency intervals
    if frequency:
        clean_series = clean_series.asfreq(frequency)
    elif clean_series.index.freq is None:
        inferred_freq = pd.infer_freq(clean_series.index)
        if inferred_freq:
            clean_series = clean_series.asfreq(inferred_freq)
            
    clean_series = clean_series.dropna()
    
    if clean_series.empty:
        raise ValueError("The time series is empty after preprocessing and frequency alignment.")
        
    # Execute Holt's Linear Trend smoothing filter
    if optimize_parameters:
        model = ExponentialSmoothing(
            clean_series,
            trend="add",
            seasonal=None,
            initialization_method="estimated"
        )
        fitted_model = model.fit(optimized=True)
    else:
        # Match fixed parameter settings based on the requested window width span
        if alpha_span is None:
            alpha_span = 30  # Default baseline lookback span parameter
        alpha_val = 2.0 / (alpha_span + 1.0)
        
        model = ExponentialSmoothing(
            clean_series,
            trend="add",
            seasonal=None,
            initialization_method="estimated"
        )
        fitted_model = model.fit(smoothing_level=alpha_val, smoothing_trend=alpha_val, optimized=False)
        
    # Extract structural state arrays (Level and Trend vectors)
    states_df = fitted_model.states
    level_vector = states_df["level"]
    trend_vector = states_df["trend"]
    
    return {
        "observed": clean_series,
        "fitted": fitted_model.fittedvalues,
        "level": level_vector,
        "trend": trend_vector,
        "model_object": fitted_model,
        "parameters": fitted_model.params
    }


def plot_double_smoothing_profile(
    smoothing_results: dict,
    title_prefix: str = "Time Series",
    y_label: str = "Values",
    save_path: str = None
) -> None:
    """
    Generates a professional, publication-grade visualization grid overlaying the 
    raw historical data with the smooth, trend-adjusted fitted models.
    
    Parameters:
    -----------
    smoothing_results : dict
        The output metric dictionary generated by apply_double_exponential_smoothing.
    title_prefix : str, default='Time Series'
        Descriptive name of the target variable for chart headers.
    y_label : str, default='Values'
        Text label for the vertical coordinate axis.
    save_path : str, optional
        File system destination path to save the completed figure file.
    """
    observed = smoothing_results["observed"]
    fitted = smoothing_results["fitted"]
    params = smoothing_results["parameters"]
    
    plt.figure(figsize=(12, 6.5))
    sns.set_theme(style="ticks")
    
    # Render the original data points with high transparency to emphasize the trends
    plt.plot(observed.index, observed.values, label="Observed History", color="#1f78b4", alpha=0.35, linewidth=1.5)
    
    # Overlay the smooth Double Exponential component trend lines
    alpha_lbl = params.get('smoothing_level', np.nan)
    beta_lbl = params.get('smoothing_trend', np.nan)
    label_text = f"Holt's Linear Trend (α={alpha_lbl:.3f}, β={beta_lbl:.3f})"
    
    plt.plot(fitted.index, fitted.values, label=label_text, color="#e31a1c", linewidth=2.2, linestyle="-")
    
    plt.title(f"{title_prefix}: Double Exponential Smoothing (Trend-Level Extraction)", fontsize=13, fontweight="bold", pad=15)
    plt.xlabel("Chronological Timeline Index", fontsize=11, labelpad=8)
    plt.ylabel(y_label, fontsize=11, labelpad=8)
    
    plt.grid(True, linestyle=":", alpha=0.5)
    plt.legend(loc="upper left", frameon=True, facecolor="white", edgecolor="none")
    
    sns.despine()
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300)
    plt.show()


def plot_smoothing_component_states(
    smoothing_results: dict,
    title_prefix: str = "Time Series",
    save_path: str = None
) -> None:
    """
    Generates a professional 2-panel stacked layout displaying the isolated internal 
    Level component and the rolling Trend velocity component separately.
    
    Parameters:
    -----------
    smoothing_results : dict
        The output metric dictionary generated by apply_double_exponential_smoothing.
    title_prefix : str, default='Time Series'
        Descriptive name of the target variable for chart headers.
    save_path : str, optional
        File system destination path to save the completed figure file.
    """
    level = smoothing_results["level"]
    trend = smoothing_results["trend"]
    
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8), sharex=True)
    
    # --- Top Panel: Isolated Smoothed Baseline Level ---
    ax1.plot(level.index, level.values, color="#7570b3", linewidth=2.0, label="Level Component (ℓ_t)")
    ax1.set_title(f"{title_prefix}: Isolated Smoothed Baseline Level (ℓ_t)", fontsize=11, fontweight="bold", loc="left")
    ax1.set_ylabel("Baseline Scaling", fontsize=11)
    ax1.grid(True, linestyle=":", alpha=0.5)
    ax1.legend(loc="upper left", frameon=True, facecolor="white")
    
    # --- Bottom Panel: Rolling Trend Directional Slope Velocity ---
    ax2.plot(trend.index, trend.values, color="#d95f02", linewidth=1.5, label="Trend Velocity Component (b_t)")
    ax2.axhline(0, color="black", linestyle="-", linewidth=0.8, alpha=0.6)
    ax2.set_title(f"{title_prefix}: Trajectory Acceleration & Slope Velocity (b_t)", fontsize=11, fontweight="bold", loc="left")
    ax2.set_ylabel("Slope / Directional Velocity", fontsize=11)
    ax2.set_xlabel("Chronological Timeline Index", fontsize=11)
    ax2.grid(True, linestyle=":", alpha=0.5)
    ax2.legend(loc="upper left", frameon=True, facecolor="white")
    
    sns.despine(ax=ax1)
    sns.despine(ax=ax2)
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300)
    plt.show()


if __name__ == "__main__":
    # Example usage with synthetically generated data to verify functionality
    np.random.seed(42)
    n_periods = 150
    time_index = pd.date_range(start="2024-01-01", periods=n_periods, freq="D")
    
    # Construct a synthetic daily dataset with an upward trend and volatile shocks
    underlying_growth = np.linspace(100, 220, n_periods)
    stochastic_noise = np.random.normal(0, 4.5, size=n_periods)
    
    # Inject a directional momentum acceleration halfway through the series
    momentum_shift = np.zeros(n_periods)
    momentum_shift[75:] = np.linspace(0, 40, 75)
    
    mock_values = underlying_growth + stochastic_noise + momentum_shift
    mock_series = pd.Series(mock_values, index=time_index, name="Simulated_Indicator")
    
    print("--- 1. Executing Double Exponential Smoothing Pipeline ---")
    results = apply_double_exponential_smoothing(mock_series, optimize_parameters=True)
    print("State extraction complete. Extracted baseline matrix head:")
    print(pd.DataFrame({"Observed": results["observed"], "Fitted": results["fitted"], "Level": results["level"], "Trend": results["trend"]}).tail(6))
    
    print("
--- 2. Launching Adaptive Trend Visualization Overlays ---")
    plot_double_smoothing_profile(results, title_prefix="Simulated Growth Asset")
    
    print("
--- 3. Launching Separated Component State Diagnosis Grid ---")
    plot_smoothing_component_states(results, title_prefix="Simulated Growth Asset")