"""
Time Shifting & Lead-Lag Feature Engineering Tool

This module provides a general-purpose, reusable framework for conducting Exploratory
Data Analysis (EDA) and feature engineering transformations on time-series data using
temporal shifts. It automates the construction of historical lookback variables (lags)
and lookahead metrics (leads), handles boundary null cells, and outputs clean, 
professional phase-alignment charts independent of specific project datasets.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


def generate_temporal_shifts(
    series: pd.Series,
    lag_steps: list = [1],
    lead_steps: list = []
) -> pd.DataFrame:
    """
    Generates a structured DataFrame containing the original series alongside
    its historical lagged columns (lookback) and future lead columns (lookahead).
    
    Parameters:
    -----------
    series : pd.Series
        The input continuous numerical time series to shift.
    lag_steps : list, default=[1]
        List of positive integers defining the historical lookback steps (Y_t-k).
    lead_steps : list, default=[]
        List of positive integers defining the future lookahead steps (Y_t+k).
        
    Returns:
    --------
    pd.DataFrame
        A DataFrame containing the aligned 'Observed' series, requested lags, 
        and requested leads columns.
    """
    if not isinstance(series, pd.Series):
        raise TypeError("The input 'series' parameter must be a valid pandas Series object.")
        
    series_name = series.name if series.name else "Target"
    results_df = pd.DataFrame(index=series.index)
    results_df["Observed"] = series
    
    # Generate historical lookback lags (shifting data forward)
    for lag in sorted(lag_steps):
        if lag <= 0:
            raise ValueError(f"Lag step must be a positive integer. Got: {lag}")
        results_df[f"{series_name}_Lag_{lag}"] = series.shift(lag)
        
    # Generate future lookahead leads (shifting data backward)
    for lead in sorted(lead_steps):
        if lead <= 0:
            raise ValueError(f"Lead step must be a positive integer. Got: {lead}")
        results_df[f"{series_name}_Lead_{lead}"] = series.shift(-lead)
        
    return results_df


def plot_temporal_phase_shift(
    shifts_df: pd.DataFrame,
    columns_to_plot: list,
    title_prefix: str = "Time Series",
    y_label: str = "Values",
    save_path: str = None
) -> None:
    """
    Generates a professional, publication-grade line plot overlaying the 
    original data with select shifted lag/lead columns to verify phase alignments.
    
    Parameters:
    -----------
    shifts_df : pd.DataFrame
        The output DataFrame generated by generate_temporal_shifts.
    columns_to_plot : list
        List of column strings from the DataFrame to include in the overlay plot.
    title_prefix : str, default='Time Series'
        Descriptive name of the target variable for chart headers.
    y_label : str, default='Values'
        Text label for the vertical coordinate axis.
    save_path : str, optional
        File system destination path to save the completed figure file.
    """
    plt.figure(figsize=(12, 6.5))
    sns.set_theme(style="ticks")
    
    # Pre-defined line styles and colors to maintain visual consistency
    styles = ["-", "--", ":", "-.", "-"]
    colors = ["#1f78b4", "#e31a1c", "#2ca02c", "#ff7f00", "#6a3d9a"]
    
    # Plot the original reference column first if included
    if "Observed" in shifts_df.columns and "Observed" in columns_to_plot:
        plt.plot(shifts_df.index, shifts_df["Observed"], label="Observed (Y_t)", 
                 color=colors[0], linewidth=2.0, linestyle=styles[0])
        columns_to_plot = [col for col in columns_to_plot if col != "Observed"]
        
    # Overlay the requested shifted columns
    for idx, col in enumerate(columns_to_plot):
        if col not in shifts_df.columns:
            continue
        style_idx = (idx + 1) % len(styles)
        color_idx = (idx + 1) % len(colors)
        
        plt.plot(shifts_df.index, shifts_df[col], label=col.replace("_", " "), 
                 color=colors[color_idx], linewidth=1.5, linestyle=styles[style_idx])
                 
    plt.title(f"{title_prefix}: Temporal Phase Shift & Lead-Lag Profile", fontsize=13, fontweight="bold", pad=15)
    plt.xlabel("Chronological Timeline Index", fontsize=11, labelpad=8)
    plt.ylabel(y_label, fontsize=11, labelpad=8)
    
    plt.grid(True, linestyle=":", alpha=0.5)
    plt.legend(loc="upper left", frameon=True, facecolor="white", edgecolor="none")
    
    sns.despine()
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300)
    plt.show()


if __name__ == "__main__":
    # Example usage with synthetically generated data to verify functionality
    np.random.seed(42)
    n_periods = 60
    time_index = pd.date_range(start="2025-01-01", periods=n_periods, freq="M")
    
    # Construct a synthetic monthly dataset with an underlying trend and cyclical path
    base_signal = np.linspace(20, 45, n_periods)
    cyclical_wave = 5.0 * np.sin(2 * np.pi * np.arange(n_periods) / 12)
    stochastic_noise = np.random.normal(0, 1.0, size=n_periods)
    
    mock_values = base_signal + cyclical_wave + stochastic_noise
    mock_series = pd.Series(mock_values, index=time_index, name="Core_Metric")
    
    print("--- 1. Executing Time Shifting Pipeline (Lag=1, Lead=1) ---")
    shifted_dataframe = generate_temporal_shifts(
        series=mock_series,
        lag_steps=[1, 2],
        lead_steps=[1]
    )
    print("Shifted matrix head preview (showing leading boundary NaNs):")
    print(shifted_dataframe.head(4))
    print("\nShifted matrix tail preview (showing trailing boundary NaNs):")
    print(shifted_dataframe.tail(4))
    
    print("
--- 2. Launching Temporal Phase Visualization Overlay ---")
    plot_temporal_phase_shift(
        shifts_df=shifted_dataframe,
        columns_to_plot=["Observed", "Core_Metric_Lag_1", "Core_Metric_Lead_1"],
        title_prefix="Simulated Operational Index",
        y_label="Metric Scaling Units"
    )