"""
Kernel Density Estimation (KDE) & Univariate Distribution Profiling Tool

This module provides a general-purpose, reusable framework for conducting Exploratory
Data Analysis (EDA) to estimate and visualize continuous probability distributions.
It handles missing value filtration, supports automated bandwidth scale optimization,
implements boundary clipping configurations, and generates clean, publication-grade
density plots with overlaid rug indicators independent of specific project columns.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


def compute_distribution_density_profile(
    series: pd.Series,
    bandwidth_adjust: float = 1.0,
    clip_bounds: tuple = None
) -> dict:
    """
    Cleans univariate sequential streams, drops missing entries, and profiles
    core empirical distribution indicators alongside continuous density metrics.
    
    Parameters:
    -----------
    series : pd.Series
        The input continuous numerical feature column to analyze.
    bandwidth_adjust : float, default=1.0
        A factor that scales the automatically calculated bandwidth. Values < 1.0 
        reveal more localized details; values > 1.0 create smoother curves.
    clip_bounds : tuple, optional
        A tuple defining strict boundaries (lower_bound, upper_bound) to truncate 
        the curve and prevent probability leakage into impossible zones.
        
    Returns:
    --------
    dict
        A dictionary containing the clean series data, basic summary statistics, 
        and reference parameter configurations.
    """
    if not isinstance(series, pd.Series):
        raise TypeError("The input 'series' parameter must be a valid pandas Series object.")
        
    # Clean out missing data rows from the column array
    clean_series = series.dropna()
    
    if clean_series.empty:
        raise ValueError("The input column sequence contains no valid numerical entries.")
        
    # Calculate core summary metrics to help interpret the distribution shape
    descriptive_stats = {
        "Sample_Size": len(clean_series),
        "Mean": clean_series.mean(),
        "Median": clean_series.median(),
        "Std_Dev": clean_series.std(),
        "Skewness": clean_series.skew(),
        "Kurtosis": clean_series.kurtosis()
    }
    
    return {
        "clean_series": clean_series,
        "statistics": descriptive_stats,
        "bandwidth_adjust": bandwidth_adjust,
        "clip_bounds": clip_bounds,
        "variable_name": series.name if series.name else "Feature_Metric"
    }


def plot_kernel_density_profile(
    density_results: dict,
    title_prefix: str = "Univariate Distribution Profile",
    fill_color: str = "#1f78b4",
    show_rug: bool = True,
    save_path: str = None
) -> None:
    """
    Generates a professional, publication-grade visualization plot rendering the continuous 
    probability density function curve with smooth fills and baseline rug data indicators.
    
    Parameters:
    -----------
    density_results : dict
        The output metric dictionary generated by compute_distribution_density_profile.
    title_prefix : str, default='Univariate Distribution Profile'
        The main descriptive title prefix for the figure header.
    fill_color : str, default='#1f78b4'
        The hex color code used to style the continuous line and its shaded area fill.
    show_rug : bool, default=True
        If True, overlays a soft rug plot along the bottom axis to show individual data points.
    save_path : str, optional
        File system destination path to save the completed figure file.
    """
    clean_data = density_results["clean_series"]
    stats = density_results["statistics"]
    var_name = density_results["variable_name"]
    bw_adj = density_results["bandwidth_adjust"]
    clip = density_results["clip_bounds"]
    
    plt.figure(figsize=(10, 6.5))
    sns.set_theme(style="ticks")
    
    # Generate the smooth continuous density estimation curve
    kde_plot = sns.kdeplot(
        data=clean_data,
        fill=True,
        color=fill_color,
        alpha=0.25,
        linewidth=2.0,
        bw_adjust=bw_adj,
        clip=clip,
        label="Empirical KDE Profile"
    )
    
    # Overlay a baseline rug plot if requested to ground the curve in actual data points
    if show_rug:
        sns.rugplot(
            data=clean_data,
            color=fill_color,
            alpha=0.4,
            height=0.03,
            ax=kde_plot
        )
        
    # Mark the localized location indicators (Mean and Median lines)
    plt.axvline(stats["Mean"], color="#e31a1c", linestyle="-", linewidth=1.5, 
                label=f"Sample Mean ({stats['Mean']:.2f})")
    plt.axvline(stats["Median"], color="#2ca02c", linestyle="--", linewidth=1.5, 
                label=f"Sample Median ({stats['Median']:.2f})")
                
    # Build a clean metadata box to present skewness and kurtosis parameters
    metadata_text = f"N = {stats['Sample_Size']}\nSkew = {stats['Skewness']:.2f}\nKurt = {stats['Kurtosis']:.2f}"
    plt.gca().text(
        0.95, 0.75, metadata_text,
        transform=plt.gca().transAxes,
        fontsize=10,
        verticalalignment='top',
        horizontalalignment='right',
        bbox=dict(boxstyle="round,pad=0.3", facecolor="white", edgecolor="gray", alpha=0.5)
    )
    
    # Configure titles, labels, and axis styling
    plt.title(f"{title_prefix}: {var_name}", fontsize=13, fontweight="bold", pad=15)
    plt.xlabel(var_name, fontsize=11, labelpad=8)
    plt.ylabel("Probability Density", fontsize=11, labelpad=8)
    
    plt.grid(True, linestyle=":", alpha=0.5)
    plt.legend(loc="upper left", frameon=True, facecolor="white", edgecolor="none")
    
    sns.despine()
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=300)
    plt.show()


if __name__ == "__main__":
    # Example usage with synthetically generated continuous data to verify functionality
    np.random.seed(42)
    n_samples = 250
    
    # Construct a synthetic bimodal mixture distribution representing two separate subpopulations
    population_1 = np.random.normal(loc=45.0, scale=5.0, size=150)
    population_2 = np.random.normal(loc=65.0, scale=4.0, size=100)
    mock_values = np.concatenate([population_1, population_2])
    
    mock_series = pd.Series(mock_values, name="Simulated_Indicator_Units")
    
    print("--- 1. Running Distribution Density Profiling Pipeline ---")
    density_output = compute_distribution_density_profile(
        series=mock_series,
        bandwidth_adjust=0.85,  # Slightly reduced value to resolve sub-modality peaks
        clip_bounds=(10.0, 90.0)
    )
    print("Calculated Summary Statistics Structure:")
    for key, value in density_output["statistics"].items():
        print(f"   {key}: {value:.4f}")
        
    print("
--- 2. Launching Continuous KDE Visualization Engine ---")
    plot_kernel_density_profile(
        density_results=density_output,
        title_prefix="Macro Feature Space Analysis",
        fill_color="#2b5c8f",
        show_rug=True
    )
"""